--BG3-50
--DROP TABLE status_booking;
--DROP TABLE bookings;
CREATE TABLE bookings (
	bkg_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
	bkg_cst_id int4 NOT NULL, 
	bkg_rm_id int4 NOT NULL,
	bkg_observations varchar(255),
	bkg_start date NOT NULL,
	bkg_end date NOT NULL,
	bkg_checkin timestamp,
	bkg_checkout timestamp,
	bkg_canceled timestamp,
	bkg_created timestamp DEFAULT current_timestamp NOT NULL,
	FOREIGN KEY(bkg_cst_id) REFERENCES customers(cst_id),
	FOREIGN KEY(bkg_rm_id) REFERENCES rooms(rm_id)
);

--BOOKINGS
INSERT INTO public.bookings (bkg_cst_id, bkg_rm_id,bkg_observations,bkg_start,bkg_end) VALUES (2,1,'dentro todo','2022-01-10','2022-01-17');
INSERT INTO public.bookings (bkg_cst_id, bkg_rm_id,bkg_observations,bkg_start,bkg_end) VALUES (2,1,'todo fuera','2022-01-01','2022-02-04');
INSERT INTO public.bookings (bkg_cst_id, bkg_rm_id,bkg_observations,bkg_start,bkg_end) VALUES (2,1,'dentro checkout','2022-01-01','2022-01-06');
INSERT INTO public.bookings (bkg_cst_id, bkg_rm_id,bkg_observations,bkg_start,bkg_end) VALUES (2,3,'dentro todo 2','2022-01-19','2022-01-25');
INSERT INTO public.bookings (bkg_cst_id, bkg_rm_id,bkg_observations,bkg_start,bkg_end) VALUES (1,1,'dentro checkin','2022-07-24','2022-02-02');
INSERT INTO public.bookings (bkg_cst_id, bkg_rm_id,bkg_observations,bkg_start,bkg_end) VALUES (2,3,'dentro limite checkin','2022-01-05','2022-01-06');
INSERT INTO public.bookings (bkg_cst_id, bkg_rm_id,bkg_observations,bkg_start,bkg_end) VALUES (2,3,'fuera checkout -limite checkout','2022-01-04','2022-01-05');
INSERT INTO public.bookings (bkg_cst_id, bkg_rm_id,bkg_observations,bkg_start,bkg_end) VALUES (2,3,'fuera todo, limite checkin-rangeout','2023-01-20','2023-01-21');
INSERT INTO public.bookings (bkg_cst_id, bkg_rm_id,bkg_observations,bkg_start,bkg_end) VALUES (2,3,'fuera todo','2023-01-21','2023-01-26');
