--BG-109,45 
--DROP TABLE hotels;
CREATE TABLE hotels ( 
	htl_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
	htl_name VARCHAR(255) UNIQUE NOT NULL,
	htl_street VARCHAR(255) NOT NULL,
	htl_city VARCHAR(255) NOT NULL,
	htl_postal_code VARCHAR(255) NOT NULL,
	htl_state VARCHAR(255) NOT NULL,
	htl_country VARCHAR(255) NOT NULL,
	htl_phone VARCHAR(255),
	htl_email VARCHAR(255),
	htl_description TEXT,
	htl_is_open int2 DEFAULT 0
);

--BG-119
--DROP TABLE public.features;
CREATE TABLE public.features (
	ftr_id int4 GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
	ftr_name varchar(255) UNIQUE NOT NULL,
	ftr_description varchar(255)
);


--BG-121
--DROP TABLE beds_combo;
CREATE TABLE beds_combo(
	bdc_id int4 GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
	bdc_name varchar(255) NOT NULL UNIQUE,
	bdc_slots int2 NOT NULL
);
/*INSERT INTO beds_combo (bdc_name,bdc_slots) values('Cama individual',1);
INSERT INTO beds_combo (bdc_name,bdc_slots) values('Dos camas individuales',2);
INSERT INTO beds_combo (bdc_name,bdc_slots) values('Tres camas individuales',3);
INSERT INTO beds_combo (bdc_name,bdc_slots) values('Cama doble',2);
INSERT INTO beds_combo (bdc_name,bdc_slots) values('Cama individual y doble ',3);
INSERT INTO beds_combo (bdc_name,bdc_slots) values('Dos camas individuales y una doble',4);
INSERT INTO beds_combo (bdc_name,bdc_slots) values('Dos camas dobles ',4);
INSERT INTO beds_combo (bdc_name,bdc_slots) values('Cama King-Size',2);
INSERT INTO beds_combo (bdc_name,bdc_slots) values('Cama individual y cama King-Size',2);
INSERT INTO beds_combo (bdc_name,bdc_slots) values('Dos camas individuales y una King-Size',4);*/



--DROP TABLE room_types;
CREATE TABLE room_types (
	rmt_id int4 GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
	rmt_name varchar(255) UNIQUE NOT NULL,	
	rmt_description varchar(255),
	rmt_price NUMERIC(7,2) NOT NULL DEFAULT 0,
	rmt_bdc_id int4 NOT NULL,
	CONSTRAINT fk_rmt_bdc_id FOREIGN KEY(rmt_bdc_id) REFERENCES beds_combo(bdc_id)
);

--DROP TABLE room_types_features;
CREATE TABLE room_types_features (
	rmt_id int4,
	ftr_id int4,
	CONSTRAINT fk_rmt_id FOREIGN KEY(rmt_id) REFERENCES room_types(rmt_id),
	CONSTRAINT fk_ftr_id FOREIGN KEY(ftr_id) REFERENCES features(ftr_id),
	PRIMARY KEY (rmt_id,ftr_id)
);

-- BG- 111
--DROP TABLE public.rooms;
CREATE TABLE public.rooms (
	rm_id int4 GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
	rm_htl_id int4 NOT NULL,
	rm_number int4 NOT NULL,
	rm_square_meters int4,
	rm_rmt_id int4,
	rm_status int2 DEFAULT 0,
	UNIQUE (rm_htl_id, rm_number),
	FOREIGN KEY (rm_htl_id) REFERENCES hotels(htl_id),
	FOREIGN KEY (rm_rmt_id) REFERENCES room_types(rmt_id)
);

--DROP TABLE public.customers;
CREATE TABLE public.customers (
	cst_id int4 GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
	cst_name varchar(255) NOT NULL,
	--cst_surnames varchar(255) NOT NULL,
	cst_surname varchar(255) NOT NULL,
	cst_docId varchar(20) NOT NULL UNIQUE ,
	--cst_identity_document varchar(9) NOT NULL UNIQUE ,
	cst_email varchar(50),
	cst_birth_date date,
	cst_address varchar(255),
	cst_nationality varchar(100) NOT NULL,
	cst_phone varchar(15) NOT NULL,
	cst_creditcard varchar(16) NOT NULL,
	cst_valid_date date NOT NULL,
	--cst_registration_date DATE DEFAULT CURRENT_DATE
);



-- BG- 117
--DROP TABLE public.status_booking;
CREATE TABLE status_booking (
 stb_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
 stb_name varchar(255) NOT NULL 
);
/*INSERT INTO status_booking (stb_name) VALUES ('confirmada');
INSERT INTO status_booking (stb_name) VALUES ('pendiente');
INSERT INTO status_booking (stb_name) VALUES ('cancelada');
INSERT INTO status_booking (stb_name) VALUES ('completada');*/

--DROP TABLE bookings;
CREATE TABLE bookings (
	bkg_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
	bkg_stb_id INTEGER NOT NULL,
	bkg_cst_id int4 NOT NULL, 
	bkg_rm_id int4 NOT NULL,
	bkg_observations varchar(255),
	bkg_checkin date NOT NULL,
	bkg_checkout date NOT NULL,
	--bkg_registration_date DATE DEFAULT CURRENT_DATE
	FOREIGN KEY(bkg_stb_id) REFERENCES status_booking(stb_id),
	FOREIGN KEY(bkg_cst_id) REFERENCES customers(cst_id),
	FOREIGN KEY(bkg_rm_id) REFERENCES rooms(rm_id)
);
-- BG- 56
--DROP TABLE public.services;
CREATE TABLE public.services (
srv_id int4 PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
srv_name varchar(255) NOT NULL UNIQUE,
srv_description varchar(255)
);

--DROP TABLE public.hotels_services;
CREATE TABLE public.hotels_services (
	htl_id int4 NOT NULL,
	srv_id int4 NOT NULL,
	CONSTRAINT hotels_services_pkey PRIMARY KEY (htl_id, srv_id)
);


-- public.hotels_services foreign keys
ALTER TABLE public.hotels_services ADD CONSTRAINT fk_htl_id FOREIGN KEY (htl_id) REFERENCES public.hotels(htl_id);
ALTER TABLE public.hotels_services ADD CONSTRAINT fk_srv_id FOREIGN KEY (srv_id) REFERENCES public.services(srv_id);


--BG-130 
--DROP table servicesExtra
CREATE TABLE servicesExtra ( 
	xtr_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
	xtr_name VARCHAR(255) UNIQUE NOT NULL,
	xtr_description varchar(255)
);