--HOTELS
INSERT INTO public.hotels (htl_name, htl_street, htl_city, htl_postal_code, htl_state, htl_country, htl_phone, htl_email, htl_description, htl_is_open) VALUES ('Atomic 01', 'Avenida Gran V�a 102', 'Vigo',36211, 'Galicia', 'Spain','+34 986 111 111','atomic01@hotlesatomic.com','Nuevo hotel de lujo.',1);
INSERT INTO public.hotels (htl_name, htl_street, htl_city, htl_postal_code, htl_state, htl_country, htl_phone, htl_email, htl_description, htl_is_open) VALUES ('Atomic 02', 'Avenida Linares Rivas ', 'A Coru�a',15005, 'Galicia', 'Spain','+34 981 222 222','atomic02@hotlesatomic.com','Nuevo hotel de lujo.',1);
INSERT INTO public.hotels (htl_name, htl_street, htl_city, htl_postal_code, htl_state, htl_country, htl_phone, htl_email, htl_description, htl_is_open) VALUES ('Atomic 03', 'Avenida Ram�n Canosa ', 'Viveiro',27869, 'Galicia', 'Spain','+34 982 333 333','atomic03@hotlesatomic.com','Nuevo hotel de lujo.',1);
INSERT INTO public.hotels (htl_name, htl_street, htl_city, htl_postal_code, htl_state, htl_country, htl_phone, htl_email, htl_description, htl_is_open) VALUES ('Atomic 04', 'Paseo de la Catellana 23', 'Madrid',28046, 'Madrid', 'Spain','+34 81 444 444','atomic04@hotlesatomic.com','Nuevo hotel de lujo.',1);
INSERT INTO public.hotels (htl_name, htl_street, htl_city, htl_postal_code, htl_state, htl_country, htl_phone, htl_email, htl_description, htl_is_open) VALUES ('Atomic 05', 'La Rambla 9', 'Barcelona',08002, 'Barcelona', 'Spain','+34 986 555 555','atomic05@hotlesatomic.com','Nuevo hotel de lujo.',1);
INSERT INTO public.hotels (htl_name, htl_street, htl_city, htl_postal_code, htl_state, htl_country, htl_phone, htl_email, htl_description, htl_is_open) VALUES ('Atomic 06', 'St James 13', 'London',1111, 'London', 'UK','+44 666 666 666','atomic06@hotlesatomic.com','Nuevo hotel de lujo.',1);
INSERT INTO public.hotels (htl_name, htl_street, htl_city, htl_postal_code, htl_state, htl_country, htl_phone, htl_email, htl_description, htl_is_open) VALUES ('Atomic 07', 'Temple Bar 23', 'Dublin',22222, 'Dublin', 'Ireland','+353 777 777 777','atomic07@hotlesatomic.com','Nuevo hotel de lujo.',1);
INSERT INTO public.hotels (htl_name, htl_street, htl_city, htl_postal_code, htl_state, htl_country, htl_phone, htl_email, htl_description, htl_is_open) VALUES ('Atomic 08', 'La Fayette 25', 'Paris',33333, 'Paris', 'France','+33 888 888 888','atomic08@hotlesatomic.com','Nuevo hotel de lujo.',0);
INSERT INTO public.hotels (htl_name, htl_street, htl_city, htl_postal_code, htl_state, htl_country, htl_phone, htl_email, htl_description, htl_is_open) VALUES ('Atomic 09', 'Avenida de Berna 26', 'Lisbon',44444, 'Lisbon', 'Portugal','+351 999 999 999','atomic09@hotlesatomic.com','Nuevo hotel de lujo.',0);
INSERT INTO public.hotels (htl_name, htl_street, htl_city, htl_postal_code, htl_state, htl_country, htl_phone, htl_email, htl_description, htl_is_open) VALUES ('Atomic 10', 'W Houston 23', 'New York City',55555, 'New York', 'EEUU','+1 101 101 010','atomic10@hotlesatomic.com','Nuevo hotel de lujo.',0);
INSERT INTO public.hotels (htl_name, htl_street, htl_city, htl_postal_code, htl_state, htl_country, htl_phone, htl_email, htl_description, htl_is_open) VALUES ('Atomic 11', 'Kokubunji-Kaido 133', 'Tokyo',66666, 'Kant?', 'Japan','+03 111 111 111','atomic11@hotlesatomic.com','Nuevo hotel de lujo.',0);
INSERT INTO public.hotels (htl_name, htl_street, htl_city, htl_postal_code, htl_state, htl_country, htl_phone, htl_email, htl_description, htl_is_open) VALUES ('Atomic 12', 'Park St 24', 'Sydney',36211, 'New South Wales', 'Australia','+61 121 121 212','atomic12@hotlesatomic.com','Nuevo hotel de lujo.',0);
INSERT INTO public.hotels (htl_name, htl_street, htl_city, htl_postal_code, htl_state, htl_country, htl_phone, htl_email, htl_description, htl_is_open) VALUES ('Atomic 13', 'Avenida Brasil 202', 'Buenos Aires',36211, 'Buenos Aires', 'Argentina','`+54 131 131 313','atomic13hotlesatomic.com','Nuevo hotel de lujo.',0);

--BEDS_COMBO
INSERT INTO public.beds_combo (bdc_name, bdc_slots) VALUES ('Cama individual',1);
INSERT INTO public.beds_combo (bdc_name, bdc_slots) VALUES ('Dos camas individuales',2);
INSERT INTO public.beds_combo (bdc_name, bdc_slots) VALUES ('Tres camas individuales',3);
INSERT INTO public.beds_combo (bdc_name, bdc_slots) VALUES ('Cama doble',2);
INSERT INTO public.beds_combo (bdc_name, bdc_slots) VALUES ('Cama individual y doble',3);
INSERT INTO public.beds_combo (bdc_name, bdc_slots) VALUES ('Dos camas individuales y una doble',4);
INSERT INTO public.beds_combo (bdc_name, bdc_slots) VALUES ('Dos camas dobles',4);
INSERT INTO public.beds_combo (bdc_name, bdc_slots) VALUES ('Cama King-size',2);
INSERT INTO public.beds_combo (bdc_name, bdc_slots) VALUES ('Cama individual y cama King-size',3);
INSERT INTO public.beds_combo (bdc_name, bdc_slots) VALUES ('Dos camas individuales y una King-size',4);

--STATUS_BOOKING
INSERT INTO public.status_booking (stb_name) VALUES ('confirmada');
INSERT INTO public.status_booking (stb_name) VALUES ('pendiente');
INSERT INTO public.status_booking (stb_name) VALUES ('cancelada');
INSERT INTO public.status_booking (stb_name) VALUES ('completada');

--ROOM_TYPES
INSERT INTO public.room_types (rmt_name,rmt_description,rmt_price,rmt_bdc_id) VALUES('Habitaci�n econ�mica simple','Habitaci�n b�sica individual',30.4,1);
INSERT INTO public.room_types (rmt_name,rmt_description,rmt_price,rmt_bdc_id) VALUES('Habitaci�n econ�mica doble','Habitaci�n b�sica doble con camas individules',40.5,2);
INSERT INTO public.room_types (rmt_name,rmt_description,rmt_price,rmt_bdc_id) VALUES('Habitaci�n econ�mica triple','Habitaci�n b�sica triple con camas individulaes',80.8,3);
INSERT INTO public.room_types (rmt_name,rmt_description,rmt_price,rmt_bdc_id) VALUES('Habitaci�n econ�mica doble superior','Habitaci�n b�sica doble con cama doble',75.8,4);
INSERT INTO public.room_types (rmt_name,rmt_description,rmt_price,rmt_bdc_id) VALUES('Habitaci�n econ�mica triple superior','Habitaci�n b�sica triple con cama doble y cama individual',90.7,5);
INSERT INTO public.room_types (rmt_name,rmt_description,rmt_price,rmt_bdc_id) VALUES('Habitaci�n cuadriple','Habitaci�n con dos camas dobles',120,6);
INSERT INTO public.room_types (rmt_name,rmt_description,rmt_price,rmt_bdc_id) VALUES('Habitaci�n boble','Habitaci�n doble king-size',60,7);
INSERT INTO public.room_types (rmt_name,rmt_description,rmt_price,rmt_bdc_id) VALUES('Habitaci�n triple','Habitaci�n triple king-size',110,8);
INSERT INTO public.room_types (rmt_name,rmt_description,rmt_price,rmt_bdc_id) VALUES('Habitaci�n cuadruple','Habitaci�n cuadruple king-size',150,9);

--ROOMS
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,101,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,102,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,103,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,104,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,105,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,106,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,107,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,108,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,201,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,202,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,203,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,204,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,205,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,206,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,207,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,208,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,301,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,302,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,303,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,304,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,305,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,306,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,307,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,308,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,401,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,402,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,403,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,404,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,405,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,406,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,407,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,408,30,9,1);

INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,101,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,102,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,103,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,104,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,105,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,106,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,107,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,108,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,201,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,202,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,203,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,204,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,205,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,206,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,207,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,208,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,301,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,302,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,303,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,304,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,305,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,306,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,307,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,308,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,401,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,402,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,403,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,404,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,405,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,406,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,407,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,408,30,9,1);

INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,101,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,102,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,103,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,104,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,105,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,106,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,107,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,108,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,201,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,202,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,203,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,204,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,205,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,206,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,207,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,208,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,301,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,302,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,303,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,304,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,305,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,306,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,307,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,308,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,401,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,402,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,403,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,404,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,405,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,406,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,407,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,408,30,9,1);

INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,101,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,102,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,103,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,104,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,105,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,106,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,107,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,108,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,201,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,202,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,203,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,204,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,205,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,206,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,207,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,208,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,301,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,302,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,303,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,304,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,305,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,306,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,307,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,308,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,401,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,402,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,403,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,404,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,405,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,406,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,407,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,408,30,9,1);

INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,101,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,102,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,103,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,104,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,105,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,106,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,107,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,108,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,201,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,202,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,203,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,204,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,205,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,206,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,207,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,208,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,301,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,302,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,303,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,304,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,305,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,306,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,307,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,308,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,401,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,402,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,403,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,404,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,405,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,406,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,407,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,408,30,9,1);

INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,101,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,102,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,103,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,104,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,105,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,106,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,107,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,108,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,201,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,202,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,203,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,204,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,205,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,206,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,207,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,208,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,301,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,302,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,303,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,304,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,305,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,306,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,307,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,308,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,401,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,402,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,403,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,404,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,405,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,406,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,407,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,408,30,9,1);

INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,101,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,102,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,103,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,104,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,105,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,106,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,107,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,108,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,201,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,202,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,203,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,204,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,205,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,206,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,207,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,208,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,301,20,7,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,302,20,7,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,303,20,7,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,304,20,7,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,305,20,7,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,306,20,7,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,307,20,7,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,308,20,7,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,401,25,8,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,402,25,8,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,403,25,8,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,404,25,8,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,405,30,9,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,406,30,9,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,407,30,9,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,408,30,9,0);

--SERVICES:
INSERT INTO public.services (ftr_name, ftr_description) VALUES ('aceptamos niños', 'Entorno ideal para los más pequeños de la casa.');
INSERT INTO public.services (srv_name, srv_description) VALUES ('Piscina infantil de bolas', 'impermeable, segura, con vigilancia, estancia perfecta para que los ni�os se diviertan');
INSERT INTO public.services (srv_name, srv_description) VALUES ('Piscina infantil de nataci�n', 'Peque�a piscina con poca profundidad ideal para ense�ar a los m�s peque�os a nadar');
INSERT INTO public.services (srv_name, srv_description) VALUES ('Gimnasio', 'Diferentes m�quinas para disfrutar entrenando y ponerse en forma');
INSERT INTO public.services (srv_name, srv_description) VALUES ('Actuaci�n de magia', 'Ideal para parejas mayores');
INSERT INTO public.services (srv_name, srv_description) VALUES ('Monitores de tiempo libre', 'Para ni�os o maridos aburridos');
INSERT INTO public.services (srv_name, srv_description) VALUES ('Zona aquapark', 'Diferentes toboganes y recorridos en "donuts", para la diversi�n de toda la familia');
INSERT INTO public.services (srv_name, srv_description) VALUES ('M�sica en vivo', 'Conciertos de j�venes talentos locales para amenizar una estudpenda velada');
INSERT INTO public.services (srv_name, srv_description) VALUES ('Pistas de p�del', '2 pistas 2vs2, y una 1vs1. Organizaci�n de torneos.');
INSERT INTO public.services (srv_name, srv_description) VALUES ('Pistas de tenis', 'Magn�ficas pistas de hierba y tierra para desestresarte y tonificarte.');
INSERT INTO public.services (srv_name, srv_description) VALUES ('Cancha de baloncesto', 'Pista exterior de baloncesto, que cuenta con las medidas oficiales.');
INSERT INTO public.services (srv_name, srv_description) VALUES ('Pista de futsal', 'Pista cubierta interior para jugar al futbito o al balonmano. Cuenta con las medidas oficiales.');
INSERT INTO public.services (ftr_name, ftr_description) VALUES ('aceptamos mascotas', 'Cuidamos de tus amigos peludos, como si fueran de nuestra familia.');
INSERT INTO public.services (ftr_name, ftr_description) VALUES ('peluquería canina', 'Nos encargamos de ofrecerles los mejores cuidados cuando nos visiten.');
INSERT INTO public.services (ftr_name, ftr_description) VALUES ('circuito canino', 'Para mantener a nuestras mascotas en buena forma y mejorar sus habilidades físicas.');

--HOTEL SERVICES:
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (1, 1);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (1, 2);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (1, 3);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (1, 4);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (1, 5);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (2, 1);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (2, 2);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (2, 3);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (2, 13);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (2, 14);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (2, 15);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (3, 1);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (3, 2);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (3, 3);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (3, 4);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (3, 7);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (3, 9);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (4, 8);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (4, 9);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (4, 11);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (4, 10);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (5, 6);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (5, 7);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (5, 8);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (5, 9);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (6, 5);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (6, 6);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (6, 7);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (7, 8);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (7, 9);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (7, 10);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (7, 11);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (8, 1);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (8, 2);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (8, 3);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (8, 8);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (8, 9);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (8, 10);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (9, 5);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (9, 6 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (9, 7 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (9, 8 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (9, 9 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (9, 10 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (9, 11 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (10,7);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (10,8);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (10,10);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (10,11);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (11,5);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (11,8);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (11,10);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (11, 11 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (12, 1 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (12, 2 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (12, 3 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (12, 5 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (12, 7 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (12, 9 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (12, 11 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (13, 1 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (13, 2 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (13, 3 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (13, 10 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (13, 11 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (13, 12 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (13, 13 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (13, 14 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (13, 15 );


--TABLAS CUSTOMERS:
--�ltima columna, credita card, no llevar�a d�a

--cambiamos tabla clientes, columna apellido, de surnames a surname. Debería estar cambiado en la tabla de creación 
--ALTER TABLE public.customers CHANGE  cst_surnames cst_surname varchar(255);

--cambiamos columna dni, por docId y le aumentamos el número de dígitos 
--ALTER TABLE public.customers CHANGE  cst_dni cst_docId varchar(9);
--ALTER TABLE public.customers MODIFY cst_docId varchar(20);

--CUSTOMERS
INSERT INTO public.customers (cst_name, cst_surname, cst_email, cst_birth_date, cst_docId, cst_address, cst_nationality,cst_phone, cst_creditcard, cst_valid_date) VALUES ('John','Smith', 'johnSmth123@gmail.com', '01/22/1980', '12345678A', '10, Downing Street, London, SWIA 2AA, United Kingdom', 'Ingl�s', '+44 07987654321', '4321987650129900', '01/10/22' );
INSERT INTO public.customers (cst_name, cst_surname, cst_email, cst_birth_date, cst_docId, cst_address, cst_nationality,cst_phone, cst_creditcard, cst_valid_date) VALUES ('Nayib','Bukele', 'naybuk@gmail.com', '06/24/1981', '023773088', '4A Calle Poniente, San Salvador, El Salvador', 'Salvadore�o', '+503 211304', '3455687650129900', '01/12/24' );
INSERT INTO public.customers (cst_name, cst_surname, cst_email, cst_birth_date, cst_docId, cst_address, cst_nationality,cst_phone, cst_creditcard, cst_valid_date) VALUES ('Diego','Guerra Goya', 'guerrita78@gmail.com', '03/20/1978', '23898620A', 'Av.Oza, num 3, 4Izq, A Coru�a, ', 'Espa�ol', '+34 636443658', '9221678950129455', '01/08/23' );
INSERT INTO public.customers (cst_name, cst_surname, cst_email, cst_birth_date, cst_docId, cst_address, cst_nationality,cst_phone, cst_creditcard, cst_valid_date) VALUES ('Ana','L�pez Estrada', 'anitadinamita@terra.es', '11/11/1984', '98765432A', 'Av.Porto, num78, 7, Vigo, Pontevedra, Espa�a', 'Espa�ola', '+34 07987654321', '4321987650129900', '01/10/22' );
INSERT INTO public.customers (cst_name, cst_surname, cst_email, cst_birth_date, cst_docId, cst_address, cst_nationality,cst_phone, cst_creditcard, cst_valid_date) VALUES ('Adam','Smith', 'capital4life@outlook.com', '10/27/1953', '12876543A', 'Edimburgo, Escocia. Direcci�n, Charlotte Square,6', 'Escoc�s', '+44 7700123456', '6781987633429900', '01/1/26' );
INSERT INTO public.customers (cst_name, cst_surname, cst_email, cst_birth_date, cst_docId, cst_address, cst_nationality,cst_phone, cst_creditcard, cst_valid_date) VALUES ('Elder','Santos', 'elder3@gmail.com', '01/22/1960', '14775678A', 'Rua nova, 56, 3Der, Oporto, Portugal', 'Portugu�s', '+351 079876543', '5621987650129222', '01/02/26' );
INSERT INTO public.customers (cst_name, cst_surname, cst_email, cst_birth_date, cst_docId, cst_address, cst_nationality,cst_phone, cst_creditcard, cst_valid_date) VALUES ('Paloma','Solana Torres', 'Patomareado@hotmail.com', '12/20/2000', '78345978A', 'Calle �palo, num5, 6, Madrid, Espa�a', 'Espa�ola', '+34 78987994321', '9998987650129900', '01/09/27' );
INSERT INTO public.customers (cst_name, cst_surname, cst_email, cst_birth_date, cst_docId, cst_address, cst_nationality,cst_phone, cst_creditcard, cst_valid_date) VALUES ('Anatoli','Karpov', 'jaquealrey@gmail.com', '01/23/1959', '77845678A', 'Calle Kr�glaia, 67, 8, Moscow, Russia', 'Ruso', '+812 633676543', '9898987650129900', '01/01/28' );
INSERT INTO public.customers (cst_name, cst_surname, cst_email, cst_birth_date, cst_docId, cst_address, cst_nationality,cst_phone, cst_creditcard, cst_valid_date) VALUES ('Antonio','Castilla L�pez', 'antopez@gmail.com', '01/11/1999', '44346678A', 'Plaza real, 34, 5I, Zaragoza, Espa�a', 'Espa�ol', '+34 96387654321', '5561987666729900', '01/11/24' );
INSERT INTO public.customers (cst_name, cst_surname, cst_email, cst_birth_date, cst_docId, cst_address, cst_nationality,cst_phone, cst_creditcard, cst_valid_date) VALUES ('Paco','Soria Lobo', 'pacobo@gmail.com', '04/12/1977', '44645678A', 'Av artabria, num56, 3, Murcia, Espa�a', 'Espa�ol', '+34 34567654321', '9871987650129900', '01/07/27' );
INSERT INTO public.customers (cst_name, cst_surname, cst_email, cst_birth_date, cst_docId, cst_address, cst_nationality,cst_phone, cst_creditcard, cst_valid_date) VALUES ('Juana','Prudant', 'juapru@gmail.com', '09/17/1967', '67845678A', 'Calle lobo, num45, 4Der, Toledo, Espa�a', 'Espa�ol', '+34 07987654321', '4556787650129900', '01/11/25' );
INSERT INTO public.customers (cst_name, cst_surname, cst_email, cst_birth_date, cst_docId, cst_address, cst_nationality,cst_phone, cst_creditcard, cst_valid_date) VALUES ('Julia','Ondas', 'jul345@gmail.com', '05/05/1980', '78945678A', 'Calle caramelo, num56, 6, La Puebla, M�xico', 'Mexicana', '+52 4831212891', '8865987650129900', '01/12/26' );

--BOOKINGS
INSERT INTO public.bookings (bkg_stb_id, bkg_cst_id, bkg_rm_id,bkg_observations,bkg_checkin,bkg_checkout) VALUES (1,2,1,'dentro todo','2022-01-10','2022-01-17');
INSERT INTO public.bookings (bkg_stb_id, bkg_cst_id, bkg_rm_id,bkg_observations,bkg_checkin,bkg_checkout) VALUES (1,2,1,'todo fuera','2022-01-01','2022-02-04');
INSERT INTO public.bookings (bkg_stb_id, bkg_cst_id, bkg_rm_id,bkg_observations,bkg_checkin,bkg_checkout) VALUES (1,2,1,'dentro checkout','2022-01-01','2022-01-06');
INSERT INTO public.bookings (bkg_stb_id, bkg_cst_id, bkg_rm_id,bkg_observations,bkg_checkin,bkg_checkout) VALUES (1,2,3,'dentro todo 2','2022-01-19','2022-01-25');
INSERT INTO public.bookings (bkg_stb_id, bkg_cst_id, bkg_rm_id,bkg_observations,bkg_checkin,bkg_checkout) VALUES (4,1,1,'dentro checkin','2022-07-24','2022-02-02');
INSERT INTO public.bookings (bkg_stb_id, bkg_cst_id, bkg_rm_id,bkg_observations,bkg_checkin,bkg_checkout) VALUES (1,2,3,'dentro limite checkin','2022-01-05','2022-01-06');
INSERT INTO public.bookings (bkg_stb_id, bkg_cst_id, bkg_rm_id,bkg_observations,bkg_checkin,bkg_checkout) VALUES (1,2,3,'fuera checkout -limite checkout','2022-01-04','2022-01-05');
INSERT INTO public.bookings (bkg_stb_id, bkg_cst_id, bkg_rm_id,bkg_observations,bkg_checkin,bkg_checkout) VALUES (1,2,3,'fuera todo, limite checkin-rangeout','2023-01-20','2023-01-21');
INSERT INTO public.bookings (bkg_stb_id, bkg_cst_id, bkg_rm_id,bkg_observations,bkg_checkin,bkg_checkout) VALUES (1,2,3,'fuera todo','2023-01-21','2023-01-26');


--FEATURES
INSERT INTO public.features (ftr_name, ftr_description) VALUES ('Zona Wifi','Wifi hotspot a trav�s de un proceso de autenticaci�n o login.');
INSERT INTO public.features (ftr_name, ftr_description) VALUES ('Insonorizaci�n','A fin de evitar ruidos molestos y permitir una mejor conciliaci�n del sue�o y descanso, dispondr� de una magn�fica insonorizaci�n de la habitaci�n y aislamiento ac�stico de las ventanas.');
INSERT INTO public.features (ftr_name, ftr_description) VALUES ('Amenities','Toallas, peines, cepillos de dientes, gel y jab�n sin aditivos, toallitas desmaquillantes y gorros de ducha.');
INSERT INTO public.features (ftr_name, ftr_description) VALUES ('Secador de pelo','Color negro. Potencia: 2500W');
INSERT INTO public.features (ftr_name, ftr_description) VALUES ('Jacuzzi','7 chorros');
INSERT INTO public.features (ftr_name, ftr_description) VALUES ('Caja fuerte','Ferrimax Serie Hotel TSW. Espesor total de las paredes: 80 mm; cada nivel de seguridad lleva un blindaje interior diferente');
INSERT INTO public.features (ftr_name, ftr_description) VALUES ('Ba�era con hidromasaje','Spatec Duo. Fabricada en fibra de vidrio reforzado con acabado acr�lico, color negro, dimensiones: 180x120x61 cm, LED de iluminaci�n subacu�tica, desinfecci�n autom�tica con ozono');
INSERT INTO public.features (ftr_name, ftr_description) VALUES ('Tv por cable','Pantalla panor�mica de 50 pulgadas, Full HD o HD Ready, conexiones USB, HDMI, MP3');



--ROOM_TYPES_FEATURES
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (1,1);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (1,2);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (1,3);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (1,4);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (2,1);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (2,2);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (2,3);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (2,4);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (3,1);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (3,2);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (3,3);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (3,4);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (4,1);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (4,2);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (4,3);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (4,4);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (5,1);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (5,2);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (5,3);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (5,4);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (6,1);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (6,2);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (6,3);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (6,4);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (6,5);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (6,6);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (7,1);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (7,2);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (7,3);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (7,4);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (7,5);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (7,6);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (8,1);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (8,2);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (8,3);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (8,4);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (8,5);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (8,6);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (8,7);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (8,8);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (9,1);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (9,2);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (9,3);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (9,4);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (9,5);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (9,6);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (9,7);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (9,8);

