--HOTELS
INSERT INTO public.hotels (htl_name, htl_street, htl_city, htl_postal_code, htl_state, htl_country, htl_phone, htl_email, htl_description, htl_is_open) VALUES ('Atomic 01', 'Avenida Gran V�a 102', 'Vigo',36211, 'Galicia', 'Spain','+34 986 111 111','atomic01@hotlesatomic.com','Nuevo hotel de lujo.',1);
INSERT INTO public.hotels (htl_name, htl_street, htl_city, htl_postal_code, htl_state, htl_country, htl_phone, htl_email, htl_description, htl_is_open) VALUES ('Atomic 02', 'Avenida Linares Rivas ', 'A Coru�a',15005, 'Galicia', 'Spain','+34 981 222 222','atomic02@hotlesatomic.com','Nuevo hotel de lujo.',1);
INSERT INTO public.hotels (htl_name, htl_street, htl_city, htl_postal_code, htl_state, htl_country, htl_phone, htl_email, htl_description, htl_is_open) VALUES ('Atomic 03', 'Avenida Ram�n Canosa ', 'Viveiro',27869, 'Galicia', 'Spain','+34 982 333 333','atomic03@hotlesatomic.com','Nuevo hotel de lujo.',1);
INSERT INTO public.hotels (htl_name, htl_street, htl_city, htl_postal_code, htl_state, htl_country, htl_phone, htl_email, htl_description, htl_is_open) VALUES ('Atomic 04', 'Paseo de la Catellana 23', 'Madrid',28046, 'Madrid', 'Spain','+34 81 444 444','atomic04@hotlesatomic.com','Nuevo hotel de lujo.',1);
INSERT INTO public.hotels (htl_name, htl_street, htl_city, htl_postal_code, htl_state, htl_country, htl_phone, htl_email, htl_description, htl_is_open) VALUES ('Atomic 05', 'La Rambla 9', 'Barcelona',08002, 'Barcelona', 'Spain','+34 986 555 555','atomic05@hotlesatomic.com','Nuevo hotel de lujo.',1);
INSERT INTO public.hotels (htl_name, htl_street, htl_city, htl_postal_code, htl_state, htl_country, htl_phone, htl_email, htl_description, htl_is_open) VALUES ('Atomic 06', 'St James 13', 'London',1111, 'London', 'UK','+44 666 666 666','atomic06@hotlesatomic.com','Nuevo hotel de lujo.',1);
INSERT INTO public.hotels (htl_name, htl_street, htl_city, htl_postal_code, htl_state, htl_country, htl_phone, htl_email, htl_description, htl_is_open) VALUES ('Atomic 07', 'Temple Bar 23', 'Dublin',22222, 'Dublin', 'Ireland','+353 777 777 777','atomic07@hotlesatomic.com','Nuevo hotel de lujo.',1);
INSERT INTO public.hotels (htl_name, htl_street, htl_city, htl_postal_code, htl_state, htl_country, htl_phone, htl_email, htl_description, htl_is_open) VALUES ('Atomic 08', 'La Fayette 25', 'Paris',33333, 'Paris', 'France','+33 888 888 888','atomic08@hotlesatomic.com','Nuevo hotel de lujo.',0);
INSERT INTO public.hotels (htl_name, htl_street, htl_city, htl_postal_code, htl_state, htl_country, htl_phone, htl_email, htl_description, htl_is_open) VALUES ('Atomic 09', 'Avenida de Berna 26', 'Lisbon',44444, 'Lisbon', 'Portugal','+351 999 999 999','atomic09@hotlesatomic.com','Nuevo hotel de lujo.',0);
INSERT INTO public.hotels (htl_name, htl_street, htl_city, htl_postal_code, htl_state, htl_country, htl_phone, htl_email, htl_description, htl_is_open) VALUES ('Atomic 10', 'W Houston 23', 'New York City',55555, 'New York', 'EEUU','+1 101 101 010','atomic10@hotlesatomic.com','Nuevo hotel de lujo.',0);
INSERT INTO public.hotels (htl_name, htl_street, htl_city, htl_postal_code, htl_state, htl_country, htl_phone, htl_email, htl_description, htl_is_open) VALUES ('Atomic 11', 'Kokubunji-Kaido 133', 'Tokyo',66666, 'Kant?', 'Japan','+03 111 111 111','atomic11@hotlesatomic.com','Nuevo hotel de lujo.',0);
INSERT INTO public.hotels (htl_name, htl_street, htl_city, htl_postal_code, htl_state, htl_country, htl_phone, htl_email, htl_description, htl_is_open) VALUES ('Atomic 12', 'Park St 24', 'Sydney',36211, 'New South Wales', 'Australia','+61 121 121 212','atomic12@hotlesatomic.com','Nuevo hotel de lujo.',0);
INSERT INTO public.hotels (htl_name, htl_street, htl_city, htl_postal_code, htl_state, htl_country, htl_phone, htl_email, htl_description, htl_is_open) VALUES ('Atomic 13', 'Avenida Brasil 202', 'Buenos Aires',36211, 'Buenos Aires', 'Argentina','`+54 131 131 313','atomic13hotlesatomic.com','Nuevo hotel de lujo.',0);

--BEDS_COMBO
INSERT INTO public.beds_combo (bdc_name, bdc_slots) VALUES ('Cama individual',1);
INSERT INTO public.beds_combo (bdc_name, bdc_slots) VALUES ('Dos camas individuales',2);
INSERT INTO public.beds_combo (bdc_name, bdc_slots) VALUES ('Tres camas individuales',3);
INSERT INTO public.beds_combo (bdc_name, bdc_slots) VALUES ('Cama doble',2);
INSERT INTO public.beds_combo (bdc_name, bdc_slots) VALUES ('Cama individual y doble',3);
INSERT INTO public.beds_combo (bdc_name, bdc_slots) VALUES ('Dos camas individuales y una doble',4);
INSERT INTO public.beds_combo (bdc_name, bdc_slots) VALUES ('Dos camas dobles',4);
INSERT INTO public.beds_combo (bdc_name, bdc_slots) VALUES ('Cama King-size',2);
INSERT INTO public.beds_combo (bdc_name, bdc_slots) VALUES ('Cama individual y cama King-size',3);
INSERT INTO public.beds_combo (bdc_name, bdc_slots) VALUES ('Dos camas individuales y una King-size',4);

--STATUS_BOOKING
INSERT INTO public.status_booking (stb_name) VALUES ('confirmada');
INSERT INTO public.status_booking (stb_name) VALUES ('pendiente');
INSERT INTO public.status_booking (stb_name) VALUES ('cancelada');
INSERT INTO public.status_booking (stb_name) VALUES ('completada');

--ROOM_TYPES
INSERT INTO public.room_types (rmt_name,rmt_description,rmt_price,rmt_bdc_id) VALUES('Habitaci�n econ�mica simple','Habitaci�n b�sica individual',30.4,1);
INSERT INTO public.room_types (rmt_name,rmt_description,rmt_price,rmt_bdc_id) VALUES('Habitaci�n econ�mica doble','Habitaci�n b�sica doble con camas individules',40.5,2);
INSERT INTO public.room_types (rmt_name,rmt_description,rmt_price,rmt_bdc_id) VALUES('Habitaci�n econ�mica triple','Habitaci�n b�sica triple con camas individulaes',80.8,3);
INSERT INTO public.room_types (rmt_name,rmt_description,rmt_price,rmt_bdc_id) VALUES('Habitaci�n econ�mica doble superior','Habitaci�n b�sica doble con cama doble',75.8,4);
INSERT INTO public.room_types (rmt_name,rmt_description,rmt_price,rmt_bdc_id) VALUES('Habitaci�n econ�mica triple superior','Habitaci�n b�sica triple con cama doble y cama individual',90.7,5);
INSERT INTO public.room_types (rmt_name,rmt_description,rmt_price,rmt_bdc_id) VALUES('Habitaci�n cuadriple','Habitaci�n con dos camas dobles',120,6);
INSERT INTO public.room_types (rmt_name,rmt_description,rmt_price,rmt_bdc_id) VALUES('Habitaci�n boble','Habitaci�n doble king-size',60,7);
INSERT INTO public.room_types (rmt_name,rmt_description,rmt_price,rmt_bdc_id) VALUES('Habitaci�n triple','Habitaci�n triple king-size',110,8);
INSERT INTO public.room_types (rmt_name,rmt_description,rmt_price,rmt_bdc_id) VALUES('Habitaci�n cuadruple','Habitaci�n cuadruple king-size',150,9);

--ROOMS
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,101,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,102,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,103,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,104,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,105,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,106,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,107,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,108,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,201,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,202,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,203,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,204,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,205,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,206,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,207,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,208,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,301,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,302,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,303,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,304,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,305,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,306,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,307,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,308,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,401,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,402,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,403,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,404,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,405,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,406,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,407,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(1,408,30,9,1);

INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,101,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,102,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,103,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,104,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,105,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,106,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,107,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,108,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,201,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,202,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,203,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,204,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,205,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,206,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,207,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,208,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,301,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,302,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,303,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,304,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,305,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,306,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,307,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,308,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,401,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,402,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,403,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,404,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,405,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,406,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,407,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(2,408,30,9,1);

INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,101,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,102,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,103,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,104,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,105,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,106,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,107,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,108,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,201,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,202,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,203,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,204,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,205,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,206,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,207,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,208,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,301,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,302,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,303,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,304,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,305,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,306,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,307,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,308,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,401,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,402,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,403,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,404,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,405,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,406,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,407,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(3,408,30,9,1);

INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,101,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,102,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,103,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,104,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,105,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,106,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,107,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,108,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,201,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,202,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,203,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,204,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,205,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,206,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,207,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,208,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,301,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,302,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,303,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,304,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,305,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,306,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,307,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,308,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,401,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,402,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,403,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,404,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,405,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,406,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,407,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(4,408,30,9,1);

INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,101,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,102,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,103,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,104,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,105,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,106,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,107,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,108,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,201,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,202,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,203,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,204,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,205,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,206,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,207,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,208,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,301,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,302,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,303,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,304,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,305,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,306,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,307,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,308,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,401,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,402,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,403,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,404,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,405,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,406,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,407,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(5,408,30,9,1);

INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,101,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,102,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,103,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,104,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,105,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,106,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,107,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,108,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,201,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,202,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,203,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,204,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,205,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,206,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,207,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,208,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,301,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,302,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,303,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,304,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,305,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,306,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,307,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,308,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,401,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,402,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,403,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,404,25,8,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,405,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,406,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,407,30,9,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(6,408,30,9,1);

INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,101,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,102,10,1,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,103,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,104,13,2,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,105,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,106,18,3,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,107,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,108,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,201,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,202,20,4,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,203,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,204,22,5,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,205,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,206,24,6,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,207,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,208,20,7,1);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,301,20,7,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,302,20,7,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,303,20,7,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,304,20,7,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,305,20,7,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,306,20,7,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,307,20,7,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,308,20,7,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,401,25,8,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,402,25,8,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,403,25,8,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,404,25,8,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,405,30,9,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,406,30,9,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,407,30,9,0);
INSERT INTO public.rooms (rm_htl_id, rm_number, rm_square_meters,rm_rmt_id,rm_status) values(7,408,30,9,0);

--SERVICES:
INSERT INTO public.services (ftr_name, ftr_description) VALUES ('aceptamos niños', 'Entorno ideal para los más pequeños de la casa.');
INSERT INTO public.services (srv_name, srv_description) VALUES ('Piscina infantil de bolas', 'impermeable, segura, con vigilancia, estancia perfecta para que los ni�os se diviertan');
INSERT INTO public.services (srv_name, srv_description) VALUES ('Piscina infantil de nataci�n', 'Peque�a piscina con poca profundidad ideal para ense�ar a los m�s peque�os a nadar');
INSERT INTO public.services (srv_name, srv_description) VALUES ('Gimnasio', 'Diferentes m�quinas para disfrutar entrenando y ponerse en forma');
INSERT INTO public.services (srv_name, srv_description) VALUES ('Actuaci�n de magia', 'Ideal para parejas mayores');
INSERT INTO public.services (srv_name, srv_description) VALUES ('Monitores de tiempo libre', 'Para ni�os o maridos aburridos');
INSERT INTO public.services (srv_name, srv_description) VALUES ('Zona aquapark', 'Diferentes toboganes y recorridos en "donuts", para la diversi�n de toda la familia');
INSERT INTO public.services (srv_name, srv_description) VALUES ('M�sica en vivo', 'Conciertos de j�venes talentos locales para amenizar una estudpenda velada');
INSERT INTO public.services (srv_name, srv_description) VALUES ('Pistas de p�del', '2 pistas 2vs2, y una 1vs1. Organizaci�n de torneos.');
INSERT INTO public.services (srv_name, srv_description) VALUES ('Pistas de tenis', 'Magn�ficas pistas de hierba y tierra para desestresarte y tonificarte.');
INSERT INTO public.services (srv_name, srv_description) VALUES ('Cancha de baloncesto', 'Pista exterior de baloncesto, que cuenta con las medidas oficiales.');
INSERT INTO public.services (srv_name, srv_description) VALUES ('Pista de futsal', 'Pista cubierta interior para jugar al futbito o al balonmano. Cuenta con las medidas oficiales.');
INSERT INTO public.services (ftr_name, ftr_description) VALUES ('aceptamos mascotas', 'Cuidamos de tus amigos peludos, como si fueran de nuestra familia.');
INSERT INTO public.services (ftr_name, ftr_description) VALUES ('peluquería canina', 'Nos encargamos de ofrecerles los mejores cuidados cuando nos visiten.');
INSERT INTO public.services (ftr_name, ftr_description) VALUES ('circuito canino', 'Para mantener a nuestras mascotas en buena forma y mejorar sus habilidades físicas.');

--HOTEL SERVICES:
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (1, 1);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (1, 2);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (1, 3);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (1, 4);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (1, 5);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (2, 1);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (2, 2);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (2, 3);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (2, 13);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (2, 14);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (2, 15);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (3, 1);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (3, 2);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (3, 3);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (3, 4);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (3, 7);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (3, 9);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (4, 8);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (4, 9);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (4, 11);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (4, 10);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (5, 6);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (5, 7);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (5, 8);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (5, 9);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (6, 5);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (6, 6);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (6, 7);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (7, 8);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (7, 9);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (7, 10);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (7, 11);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (8, 1);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (8, 2);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (8, 3);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (8, 8);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (8, 9);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (8, 10);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (9, 5);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (9, 6 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (9, 7 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (9, 8 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (9, 9 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (9, 10 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (9, 11 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (10,7);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (10,8);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (10,10);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (10,11);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (11,5);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (11,8);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (11,10);
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (11, 11 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (12, 1 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (12, 2 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (12, 3 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (12, 5 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (12, 7 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (12, 9 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (12, 11 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (13, 1 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (13, 2 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (13, 3 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (13, 10 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (13, 11 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (13, 12 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (13, 13 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (13, 14 );
INSERT INTO public.hotels_services (htl_id, srv_id) VALUES (13, 15 );


--TABLAS CUSTOMERS:
--�ltima columna, credita card, no llevar�a d�a

--cambiamos tabla clientes, columna apellido, de surnames a surname. Debería estar cambiado en la tabla de creación 
--ALTER TABLE public.customers CHANGE  cst_surnames cst_surname varchar(255);

--cambiamos columna dni, por docId y le aumentamos el número de dígitos 
--ALTER TABLE public.customers CHANGE  cst_dni cst_docId varchar(9);
--ALTER TABLE public.customers MODIFY cst_docId varchar(20);

--CUSTOMERS
INSERT INTO public.customers (cst_name, cst_surname, cst_email, cst_birth_date, cst_docId, cst_address, cst_nationality,cst_phone, cst_creditcard, cst_valid_date) VALUES ('John','Smith', 'johnSmth123@gmail.com', '01/22/1980', '12345678A', '10, Downing Street, London, SWIA 2AA, United Kingdom', 'Ingl�s', '+44 07987654321', '4321987650129900', '01/10/22' );
INSERT INTO public.customers (cst_name, cst_surname, cst_email, cst_birth_date, cst_docId, cst_address, cst_nationality,cst_phone, cst_creditcard, cst_valid_date) VALUES ('Nayib','Bukele', 'naybuk@gmail.com', '06/24/1981', '023773088', '4A Calle Poniente, San Salvador, El Salvador', 'Salvadore�o', '+503 211304', '3455687650129900', '01/12/24' );
INSERT INTO public.customers (cst_name, cst_surname, cst_email, cst_birth_date, cst_docId, cst_address, cst_nationality,cst_phone, cst_creditcard, cst_valid_date) VALUES ('Diego','Guerra Goya', 'guerrita78@gmail.com', '03/20/1978', '23898620A', 'Av.Oza, num 3, 4Izq, A Coru�a, ', 'Espa�ol', '+34 636443658', '9221678950129455', '01/08/23' );
INSERT INTO public.customers (cst_name, cst_surname, cst_email, cst_birth_date, cst_docId, cst_address, cst_nationality,cst_phone, cst_creditcard, cst_valid_date) VALUES ('Ana','L�pez Estrada', 'anitadinamita@terra.es', '11/11/1984', '98765432A', 'Av.Porto, num78, 7, Vigo, Pontevedra, Espa�a', 'Espa�ola', '+34 07987654321', '4321987650129900', '01/10/22' );
INSERT INTO public.customers (cst_name, cst_surname, cst_email, cst_birth_date, cst_docId, cst_address, cst_nationality,cst_phone, cst_creditcard, cst_valid_date) VALUES ('Adam','Smith', 'capital4life@outlook.com', '10/27/1953', '12876543A', 'Edimburgo, Escocia. Direcci�n, Charlotte Square,6', 'Escoc�s', '+44 7700123456', '6781987633429900', '01/1/26' );
INSERT INTO public.customers (cst_name, cst_surname, cst_email, cst_birth_date, cst_docId, cst_address, cst_nationality,cst_phone, cst_creditcard, cst_valid_date) VALUES ('Elder','Santos', 'elder3@gmail.com', '01/22/1960', '14775678A', 'Rua nova, 56, 3Der, Oporto, Portugal', 'Portugu�s', '+351 079876543', '5621987650129222', '01/02/26' );
INSERT INTO public.customers (cst_name, cst_surname, cst_email, cst_birth_date, cst_docId, cst_address, cst_nationality,cst_phone, cst_creditcard, cst_valid_date) VALUES ('Paloma','Solana Torres', 'Patomareado@hotmail.com', '12/20/2000', '78345978A', 'Calle �palo, num5, 6, Madrid, Espa�a', 'Espa�ola', '+34 78987994321', '9998987650129900', '01/09/27' );
INSERT INTO public.customers (cst_name, cst_surname, cst_email, cst_birth_date, cst_docId, cst_address, cst_nationality,cst_phone, cst_creditcard, cst_valid_date) VALUES ('Anatoli','Karpov', 'jaquealrey@gmail.com', '01/23/1959', '77845678A', 'Calle Kr�glaia, 67, 8, Moscow, Russia', 'Ruso', '+812 633676543', '9898987650129900', '01/01/28' );
INSERT INTO public.customers (cst_name, cst_surname, cst_email, cst_birth_date, cst_docId, cst_address, cst_nationality,cst_phone, cst_creditcard, cst_valid_date) VALUES ('Antonio','Castilla L�pez', 'antopez@gmail.com', '01/11/1999', '44346678A', 'Plaza real, 34, 5I, Zaragoza, Espa�a', 'Espa�ol', '+34 96387654321', '5561987666729900', '01/11/24' );
INSERT INTO public.customers (cst_name, cst_surname, cst_email, cst_birth_date, cst_docId, cst_address, cst_nationality,cst_phone, cst_creditcard, cst_valid_date) VALUES ('Paco','Soria Lobo', 'pacobo@gmail.com', '04/12/1977', '44645678A', 'Av artabria, num56, 3, Murcia, Espa�a', 'Espa�ol', '+34 34567654321', '9871987650129900', '01/07/27' );
INSERT INTO public.customers (cst_name, cst_surname, cst_email, cst_birth_date, cst_docId, cst_address, cst_nationality,cst_phone, cst_creditcard, cst_valid_date) VALUES ('Juana','Prudant', 'juapru@gmail.com', '09/17/1967', '67845678A', 'Calle lobo, num45, 4Der, Toledo, Espa�a', 'Espa�ol', '+34 07987654321', '4556787650129900', '01/11/25' );
INSERT INTO public.customers (cst_name, cst_surname, cst_email, cst_birth_date, cst_docId, cst_address, cst_nationality,cst_phone, cst_creditcard, cst_valid_date) VALUES ('Julia','Ondas', 'jul345@gmail.com', '05/05/1980', '78945678A', 'Calle caramelo, num56, 6, La Puebla, M�xico', 'Mexicana', '+52 4831212891', '8865987650129900', '01/12/26' );

--BOOKINGS
INSERT INTO public.bookings (bkg_stb_id, bkg_cst_id, bkg_rm_id,bkg_observations,bkg_checkin,bkg_checkout) VALUES (1,2,1,'dentro todo','2022-01-10','2022-01-17');
INSERT INTO public.bookings (bkg_stb_id, bkg_cst_id, bkg_rm_id,bkg_observations,bkg_checkin,bkg_checkout) VALUES (1,2,1,'todo fuera','2022-01-01','2022-02-04');
INSERT INTO public.bookings (bkg_stb_id, bkg_cst_id, bkg_rm_id,bkg_observations,bkg_checkin,bkg_checkout) VALUES (1,2,1,'dentro checkout','2022-01-01','2022-01-06');
INSERT INTO public.bookings (bkg_stb_id, bkg_cst_id, bkg_rm_id,bkg_observations,bkg_checkin,bkg_checkout) VALUES (1,2,3,'dentro todo 2','2022-01-19','2022-01-25');
INSERT INTO public.bookings (bkg_stb_id, bkg_cst_id, bkg_rm_id,bkg_observations,bkg_checkin,bkg_checkout) VALUES (4,1,1,'dentro checkin','2022-07-24','2022-02-02');
INSERT INTO public.bookings (bkg_stb_id, bkg_cst_id, bkg_rm_id,bkg_observations,bkg_checkin,bkg_checkout) VALUES (1,2,3,'dentro limite checkin','2022-01-05','2022-01-06');
INSERT INTO public.bookings (bkg_stb_id, bkg_cst_id, bkg_rm_id,bkg_observations,bkg_checkin,bkg_checkout) VALUES (1,2,3,'fuera checkout -limite checkout','2022-01-04','2022-01-05');
INSERT INTO public.bookings (bkg_stb_id, bkg_cst_id, bkg_rm_id,bkg_observations,bkg_checkin,bkg_checkout) VALUES (1,2,3,'fuera todo, limite checkin-rangeout','2023-01-20','2023-01-21');
INSERT INTO public.bookings (bkg_stb_id, bkg_cst_id, bkg_rm_id,bkg_observations,bkg_checkin,bkg_checkout) VALUES (1,2,3,'fuera todo','2023-01-21','2023-01-26');


--FEATURES
INSERT INTO public.features (ftr_name, ftr_description) VALUES ('Zona Wifi','Wifi hotspot a trav�s de un proceso de autenticaci�n o login.');
INSERT INTO public.features (ftr_name, ftr_description) VALUES ('Insonorizaci�n','A fin de evitar ruidos molestos y permitir una mejor conciliaci�n del sue�o y descanso, dispondr� de una magn�fica insonorizaci�n de la habitaci�n y aislamiento ac�stico de las ventanas.');
INSERT INTO public.features (ftr_name, ftr_description) VALUES ('Amenities','Toallas, peines, cepillos de dientes, gel y jab�n sin aditivos, toallitas desmaquillantes y gorros de ducha.');
INSERT INTO public.features (ftr_name, ftr_description) VALUES ('Secador de pelo','Color negro. Potencia: 2500W');
INSERT INTO public.features (ftr_name, ftr_description) VALUES ('Jacuzzi','7 chorros');
INSERT INTO public.features (ftr_name, ftr_description) VALUES ('Caja fuerte','Ferrimax Serie Hotel TSW. Espesor total de las paredes: 80 mm; cada nivel de seguridad lleva un blindaje interior diferente');
INSERT INTO public.features (ftr_name, ftr_description) VALUES ('Ba�era con hidromasaje','Spatec Duo. Fabricada en fibra de vidrio reforzado con acabado acr�lico, color negro, dimensiones: 180x120x61 cm, LED de iluminaci�n subacu�tica, desinfecci�n autom�tica con ozono');
INSERT INTO public.features (ftr_name, ftr_description) VALUES ('Tv por cable','Pantalla panor�mica de 50 pulgadas, Full HD o HD Ready, conexiones USB, HDMI, MP3');



--ROOM_TYPES_FEATURES
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (1,1);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (1,2);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (1,3);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (1,4);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (2,1);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (2,2);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (2,3);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (2,4);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (3,1);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (3,2);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (3,3);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (3,4);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (4,1);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (4,2);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (4,3);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (4,4);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (5,1);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (5,2);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (5,3);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (5,4);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (6,1);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (6,2);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (6,3);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (6,4);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (6,5);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (6,6);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (7,1);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (7,2);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (7,3);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (7,4);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (7,5);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (7,6);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (8,1);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (8,2);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (8,3);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (8,4);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (8,5);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (8,6);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (8,7);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (8,8);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (9,1);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (9,2);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (9,3);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (9,4);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (9,5);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (9,6);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (9,7);
INSERT INTO public.room_types_features (rmt_id,ftr_id) VALUES (9,8);

--COUNTRIES

INSERT INTO countries VALUES(1, 'AF', 'Afganistán');
INSERT INTO countries VALUES(2, 'AX', 'Islas Gland');
INSERT INTO countries VALUES(3, 'AL', 'Albania');
INSERT INTO countries VALUES(4, 'DE', 'Alemania');
INSERT INTO countries VALUES(5, 'AD', 'Andorra');
INSERT INTO countries VALUES(6, 'AO', 'Angola');
INSERT INTO countries VALUES(7, 'AI', 'Anguilla');
INSERT INTO countries VALUES(8, 'AQ', 'Antártida');
INSERT INTO countries VALUES(9, 'AG', 'Antigua y Barbuda');
INSERT INTO countries VALUES(10, 'AN', 'Antillas Holandesas');
INSERT INTO countries VALUES(11, 'SA', 'Arabia Saudí');
INSERT INTO countries VALUES(12, 'DZ', 'Argelia');
INSERT INTO countries VALUES(13, 'AR', 'Argentina');
INSERT INTO countries VALUES(14, 'AM', 'Armenia');
INSERT INTO countries VALUES(15, 'AW', 'Aruba');
INSERT INTO countries VALUES(16, 'AU', 'Australia');
INSERT INTO countries VALUES(17, 'AT', 'Austria');
INSERT INTO countries VALUES(18, 'AZ', 'Azerbaiyán');
INSERT INTO countries VALUES(19, 'BS', 'Bahamas');
INSERT INTO countries VALUES(20, 'BH', 'Bahréin');
INSERT INTO countries VALUES(21, 'BD', 'Bangladesh');
INSERT INTO countries VALUES(22, 'BB', 'Barbados');
INSERT INTO countries VALUES(23, 'BY', 'Bielorrusia');
INSERT INTO countries VALUES(24, 'BE', 'Bélgica');
INSERT INTO countries VALUES(25, 'BZ', 'Belice');
INSERT INTO countries VALUES(26, 'BJ', 'Benin');
INSERT INTO countries VALUES(27, 'BM', 'Bermudas');
INSERT INTO countries VALUES(28, 'BT', 'Bhután');
INSERT INTO countries VALUES(29, 'BO', 'Bolivia');
INSERT INTO countries VALUES(30, 'BA', 'Bosnia y Herzegovina');
INSERT INTO countries VALUES(31, 'BW', 'Botsuana');
INSERT INTO countries VALUES(32, 'BV', 'Isla Bouvet');
INSERT INTO countries VALUES(33, 'BR', 'Brasil');
INSERT INTO countries VALUES(34, 'BN', 'Brunéi');
INSERT INTO countries VALUES(35, 'BG', 'Bulgaria');
INSERT INTO countries VALUES(36, 'BF', 'Burkina Faso');
INSERT INTO countries VALUES(37, 'BI', 'Burundi');
INSERT INTO countries VALUES(38, 'CV', 'Cabo Verde');
INSERT INTO countries VALUES(39, 'KY', 'Islas Caimán');
INSERT INTO countries VALUES(40, 'KH', 'Camboya');
INSERT INTO countries VALUES(41, 'CM', 'Camerún');
INSERT INTO countries VALUES(42, 'CA', 'Canadá');
INSERT INTO countries VALUES(43, 'CF', 'República Centroafricana');
INSERT INTO countries VALUES(44, 'TD', 'Chad');
INSERT INTO countries VALUES(45, 'CZ', 'República Checa');
INSERT INTO countries VALUES(46, 'CL', 'Chile');
INSERT INTO countries VALUES(47, 'CN', 'China');
INSERT INTO countries VALUES(48, 'CY', 'Chipre');
INSERT INTO countries VALUES(49, 'CX', 'Isla de Navidad');
INSERT INTO countries VALUES(50, 'VA', 'Ciudad del Vaticano');
INSERT INTO countries VALUES(51, 'CC', 'Islas Cocos');
INSERT INTO countries VALUES(52, 'CO', 'Colombia');
INSERT INTO countries VALUES(53, 'KM', 'Comoras');
INSERT INTO countries VALUES(54, 'CD', 'República Democrática del Congo');
INSERT INTO countries VALUES(55, 'CG', 'Congo');
INSERT INTO countries VALUES(56, 'CK', 'Islas Cook');
INSERT INTO countries VALUES(57, 'KP', 'Corea del Norte');
INSERT INTO countries VALUES(58, 'KR', 'Corea del Sur');
INSERT INTO countries VALUES(59, 'CI', 'Costa de Marfil');
INSERT INTO countries VALUES(60, 'CR', 'Costa Rica');
INSERT INTO countries VALUES(61, 'HR', 'Croacia');
INSERT INTO countries VALUES(62, 'CU', 'Cuba');
INSERT INTO countries VALUES(63, 'DK', 'Dinamarca');
INSERT INTO countries VALUES(64, 'DM', 'Dominica');
INSERT INTO countries VALUES(65, 'DO', 'República Dominicana');
INSERT INTO countries VALUES(66, 'EC', 'Ecuador');
INSERT INTO countries VALUES(67, 'EG', 'Egipto');
INSERT INTO countries VALUES(68, 'SV', 'El Salvador');
INSERT INTO countries VALUES(69, 'AE', 'Emiratos Árabes Unidos');
INSERT INTO countries VALUES(70, 'ER', 'Eritrea');
INSERT INTO countries VALUES(71, 'SK', 'Eslovaquia');
INSERT INTO countries VALUES(72, 'SI', 'Eslovenia');
INSERT INTO countries VALUES(73, 'ES', 'España');
INSERT INTO countries VALUES(74, 'UM', 'Islas ultramarinas de Estados Unidos');
INSERT INTO countries VALUES(75, 'US', 'Estados Unidos');
INSERT INTO countries VALUES(76, 'EE', 'Estonia');
INSERT INTO countries VALUES(77, 'ET', 'Etiopía');
INSERT INTO countries VALUES(78, 'FO', 'Islas Feroe');
INSERT INTO countries VALUES(79, 'PH', 'Filipinas');
INSERT INTO countries VALUES(80, 'FI', 'Finlandia');
INSERT INTO countries VALUES(81, 'FJ', 'Fiyi');
INSERT INTO countries VALUES(82, 'FR', 'Francia');
INSERT INTO countries VALUES(83, 'GA', 'Gabón');
INSERT INTO countries VALUES(84, 'GM', 'Gambia');
INSERT INTO countries VALUES(85, 'GE', 'Georgia');
INSERT INTO countries VALUES(86, 'GS', 'Islas Georgias del Sur y Sandwich del Sur');
INSERT INTO countries VALUES(87, 'GH', 'Ghana');
INSERT INTO countries VALUES(88, 'GI', 'Gibraltar');
INSERT INTO countries VALUES(89, 'GD', 'Granada');
INSERT INTO countries VALUES(90, 'GR', 'Grecia');
INSERT INTO countries VALUES(91, 'GL', 'Groenlandia');
INSERT INTO countries VALUES(92, 'GP', 'Guadalupe');
INSERT INTO countries VALUES(93, 'GU', 'Guam');
INSERT INTO countries VALUES(94, 'GT', 'Guatemala');
INSERT INTO countries VALUES(95, 'GF', 'Guayana Francesa');
INSERT INTO countries VALUES(96, 'GN', 'Guinea');
INSERT INTO countries VALUES(97, 'GQ', 'Guinea Ecuatorial');
INSERT INTO countries VALUES(98, 'GW', 'Guinea-Bissau');
INSERT INTO countries VALUES(99, 'GY', 'Guyana');
INSERT INTO countries VALUES(100, 'HT', 'Haití');
INSERT INTO countries VALUES(101, 'HM', 'Islas Heard y McDonald');
INSERT INTO countries VALUES(102, 'HN', 'Honduras');
INSERT INTO countries VALUES(103, 'HK', 'Hong Kong');
INSERT INTO countries VALUES(104, 'HU', 'Hungría');
INSERT INTO countries VALUES(105, 'IN', 'India');
INSERT INTO countries VALUES(106, 'ID', 'Indonesia');
INSERT INTO countries VALUES(107, 'IR', 'Irán');
INSERT INTO countries VALUES(108, 'IQ', 'Iraq');
INSERT INTO countries VALUES(109, 'IE', 'Irlanda');
INSERT INTO countries VALUES(110, 'IS', 'Islandia');
INSERT INTO countries VALUES(111, 'IL', 'Israel');
INSERT INTO countries VALUES(112, 'IT', 'Italia');
INSERT INTO countries VALUES(113, 'JM', 'Jamaica');
INSERT INTO countries VALUES(114, 'JP', 'Japón');
INSERT INTO countries VALUES(115, 'JO', 'Jordania');
INSERT INTO countries VALUES(116, 'KZ', 'Kazajstán');
INSERT INTO countries VALUES(117, 'KE', 'Kenia');
INSERT INTO countries VALUES(118, 'KG', 'Kirguistán');
INSERT INTO countries VALUES(119, 'KI', 'Kiribati');
INSERT INTO countries VALUES(120, 'KW', 'Kuwait');
INSERT INTO countries VALUES(121, 'LA', 'Laos');
INSERT INTO countries VALUES(122, 'LS', 'Lesotho');
INSERT INTO countries VALUES(123, 'LV', 'Letonia');
INSERT INTO countries VALUES(124, 'LB', 'Líbano');
INSERT INTO countries VALUES(125, 'LR', 'Liberia');
INSERT INTO countries VALUES(126, 'LY', 'Libia');
INSERT INTO countries VALUES(127, 'LI', 'Liechtenstein');
INSERT INTO countries VALUES(128, 'LT', 'Lituania');
INSERT INTO countries VALUES(129, 'LU', 'Luxemburgo');
INSERT INTO countries VALUES(130, 'MO', 'Macao');
INSERT INTO countries VALUES(131, 'MK', 'ARY Macedonia');
INSERT INTO countries VALUES(132, 'MG', 'Madagascar');
INSERT INTO countries VALUES(133, 'MY', 'Malasia');
INSERT INTO countries VALUES(134, 'MW', 'Malawi');
INSERT INTO countries VALUES(135, 'MV', 'Maldivas');
INSERT INTO countries VALUES(136, 'ML', 'Malí');
INSERT INTO countries VALUES(137, 'MT', 'Malta');
INSERT INTO countries VALUES(138, 'FK', 'Islas Malvinas');
INSERT INTO countries VALUES(139, 'MP', 'Islas Marianas del Norte');
INSERT INTO countries VALUES(140, 'MA', 'Marruecos');
INSERT INTO countries VALUES(141, 'MH', 'Islas Marshall');
INSERT INTO countries VALUES(142, 'MQ', 'Martinica');
INSERT INTO countries VALUES(143, 'MU', 'Mauricio');
INSERT INTO countries VALUES(144, 'MR', 'Mauritania');
INSERT INTO countries VALUES(145, 'YT', 'Mayotte');
INSERT INTO countries VALUES(146, 'MX', 'México');
INSERT INTO countries VALUES(147, 'FM', 'Micronesia');
INSERT INTO countries VALUES(148, 'MD', 'Moldavia');
INSERT INTO countries VALUES(149, 'MC', 'Mónaco');
INSERT INTO countries VALUES(150, 'MN', 'Mongolia');
INSERT INTO countries VALUES(151, 'MS', 'Montserrat');
INSERT INTO countries VALUES(152, 'MZ', 'Mozambique');
INSERT INTO countries VALUES(153, 'MM', 'Myanmar');
INSERT INTO countries VALUES(154, 'NA', 'Namibia');
INSERT INTO countries VALUES(155, 'NR', 'Nauru');
INSERT INTO countries VALUES(156, 'NP', 'Nepal');
INSERT INTO countries VALUES(157, 'NI', 'Nicaragua');
INSERT INTO countries VALUES(158, 'NE', 'Níger');
INSERT INTO countries VALUES(159, 'NG', 'Nigeria');
INSERT INTO countries VALUES(160, 'NU', 'Niue');
INSERT INTO countries VALUES(161, 'NF', 'Isla Norfolk');
INSERT INTO countries VALUES(162, 'NO', 'Noruega');
INSERT INTO countries VALUES(163, 'NC', 'Nueva Caledonia');
INSERT INTO countries VALUES(164, 'NZ', 'Nueva Zelanda');
INSERT INTO countries VALUES(165, 'OM', 'Omán');
INSERT INTO countries VALUES(166, 'NL', 'Países Bajos');
INSERT INTO countries VALUES(167, 'PK', 'Pakistán');
INSERT INTO countries VALUES(168, 'PW', 'Palau');
INSERT INTO countries VALUES(169, 'PS', 'Palestina');
INSERT INTO countries VALUES(170, 'PA', 'Panamá');
INSERT INTO countries VALUES(171, 'PG', 'Papúa Nueva Guinea');
INSERT INTO countries VALUES(172, 'PY', 'Paraguay');
INSERT INTO countries VALUES(173, 'PE', 'Perú');
INSERT INTO countries VALUES(174, 'PN', 'Islas Pitcairn');
INSERT INTO countries VALUES(175, 'PF', 'Polinesia Francesa');
INSERT INTO countries VALUES(176, 'PL', 'Polonia');
INSERT INTO countries VALUES(177, 'PT', 'Portugal');
INSERT INTO countries VALUES(178, 'PR', 'Puerto Rico');
INSERT INTO countries VALUES(179, 'QA', 'Qatar');
INSERT INTO countries VALUES(180, 'GB', 'Reino Unido');
INSERT INTO countries VALUES(181, 'RE', 'Reunión');
INSERT INTO countries VALUES(182, 'RW', 'Ruanda');
INSERT INTO countries VALUES(183, 'RO', 'Rumania');
INSERT INTO countries VALUES(184, 'RU', 'Rusia');
INSERT INTO countries VALUES(185, 'EH', 'Sahara Occidental');
INSERT INTO countries VALUES(186, 'SB', 'Islas Salomón');
INSERT INTO countries VALUES(187, 'WS', 'Samoa');
INSERT INTO countries VALUES(188, 'AS', 'Samoa Americana');
INSERT INTO countries VALUES(189, 'KN', 'San Cristóbal y Nevis');
INSERT INTO countries VALUES(190, 'SM', 'San Marino');
INSERT INTO countries VALUES(191, 'PM', 'San Pedro y Miquelón');
INSERT INTO countries VALUES(192, 'VC', 'San Vicente y las Granadinas');
INSERT INTO countries VALUES(193, 'SH', 'Santa Helena');
INSERT INTO countries VALUES(194, 'LC', 'Santa Lucía');
INSERT INTO countries VALUES(195, 'ST', 'Santo Tomé y Príncipe');
INSERT INTO countries VALUES(196, 'SN', 'Senegal');
INSERT INTO countries VALUES(197, 'CS', 'Serbia y Montenegro');
INSERT INTO countries VALUES(198, 'SC', 'Seychelles');
INSERT INTO countries VALUES(199, 'SL', 'Sierra Leona');
INSERT INTO countries VALUES(200, 'SG', 'Singapur');
INSERT INTO countries VALUES(201, 'SY', 'Siria');
INSERT INTO countries VALUES(202, 'SO', 'Somalia');
INSERT INTO countries VALUES(203, 'LK', 'Sri Lanka');
INSERT INTO countries VALUES(204, 'SZ', 'Suazilandia');
INSERT INTO countries VALUES(205, 'ZA', 'Sudáfrica');
INSERT INTO countries VALUES(206, 'SD', 'Sudán');
INSERT INTO countries VALUES(207, 'SE', 'Suecia');
INSERT INTO countries VALUES(208, 'CH', 'Suiza');
INSERT INTO countries VALUES(209, 'SR', 'Surinam');
INSERT INTO countries VALUES(210, 'SJ', 'Svalbard y Jan Mayen');
INSERT INTO countries VALUES(211, 'TH', 'Tailandia');
INSERT INTO countries VALUES(212, 'TW', 'Taiwán');
INSERT INTO countries VALUES(213, 'TZ', 'Tanzania');
INSERT INTO countries VALUES(214, 'TJ', 'Tayikistán');
INSERT INTO countries VALUES(215, 'IO', 'Territorio Británico del Océano Índico');
INSERT INTO countries VALUES(216, 'TF', 'Territorios Australes Franceses');
INSERT INTO countries VALUES(217, 'TL', 'Timor Oriental');
INSERT INTO countries VALUES(218, 'TG', 'Togo');
INSERT INTO countries VALUES(219, 'TK', 'Tokelau');
INSERT INTO countries VALUES(220, 'TO', 'Tonga');
INSERT INTO countries VALUES(221, 'TT', 'Trinidad y Tobago');
INSERT INTO countries VALUES(222, 'TN', 'Túnez');
INSERT INTO countries VALUES(223, 'TC', 'Islas Turcas y Caicos');
INSERT INTO countries VALUES(224, 'TM', 'Turkmenistán');
INSERT INTO countries VALUES(225, 'TR', 'Turquía');
INSERT INTO countries VALUES(226, 'TV', 'Tuvalu');
INSERT INTO countries VALUES(227, 'UA', 'Ucrania');
INSERT INTO countries VALUES(228, 'UG', 'Uganda');
INSERT INTO countries VALUES(229, 'UY', 'Uruguay');
INSERT INTO countries VALUES(230, 'UZ', 'Uzbekistán');
INSERT INTO countries VALUES(231, 'VU', 'Vanuatu');
INSERT INTO countries VALUES(232, 'VE', 'Venezuela');
INSERT INTO countries VALUES(233, 'VN', 'Vietnam');
INSERT INTO countries VALUES(234, 'VG', 'Islas Vírgenes Británicas');
INSERT INTO countries VALUES(235, 'VI', 'Islas Vírgenes de los Estados Unidos');
INSERT INTO countries VALUES(236, 'WF', 'Wallis y Futuna');
INSERT INTO countries VALUES(237, 'YE', 'Yemen');
INSERT INTO countries VALUES(238, 'DJ', 'Yibuti');
INSERT INTO countries VALUES(239, 'ZM', 'Zambia');
INSERT INTO countries VALUES(240, 'ZW', 'Zimbabue');
