package com.ontimize.atomicHotelsApiRest.model.core.tools;

public class TypeCodes {

	public static enum type {
		STRING, INTEGER, INTEGER_UNSIGNED, LONG, LONG_UNSIGNED, DOUBLE, DOUBLE_UNSIGNED, PRICE, EMAIL, CREDIT_CARD,
		PHONE, DATE, DATETIME, ACTION, BOOLEAN, COUNTRY, EXPIRATION_DATE, BOOKING_ACTION, CUSTOMER_ACTION
	};

}