package com.ontimize.atomicHotelsApiRest.model.core.tools;

public class TypeCodes {

	public static enum type {
		TEXT, NO_EMPTY_TEXT, STRING, NO_EMPTY_STRING, SMALL_STRING, NO_EMPTY_SMALL_STRING, INTEGER, INTEGER_UNSIGNED,
		LONG, LONG_UNSIGNED, DOUBLE, DOUBLE_UNSIGNED, PRICE, EMAIL, DNI, CREDIT_CARD, PHONE, DATE, DATETIME, ACTION,
		BOOLEAN, COUNTRY, EXPIRATION_DATE, BOOKING_ACTION, CUSTOMER_ACTION, USER_ACTION, BYTETEA, USER_ROLE, FLOAT
	};

}